### ISSUE TITLE
more sample attenuation needed to avoid clipping

### ISSUE THREAD

**Issue by mrbumpy409** [musescore/sftools#15]
sftools attenuates the samples before compressing them, supposedly to work around a libsndfile bug. However, attenuating the samples is a good practice before compressing to lossy formats regardless of any bugs, because the conversion will always result in some peaks being higher than the original files, potentially leading to clipping. The general recommendation is to have 0.5 - 1 dB headroom before converting to OGG, MP3, M4A, etc.

If I convert the new piano I have created for MuseScore to SF3 using Polyphone, many of the samples make an audible popping noise where they are now clipping. If I manually attenuate the sample data by 0.5 dB (by editing the SF2 as RAW audio in Audacity), some of the samples still clip. Attenuating by 1 dB eliminates all clipping.

When I do the conversion via sftools, only a few samples clip, but we need none of them to clip. sfont.cpp line #1234 is where this attenuation is done in sftools, but I don't understand what calculations are happening there to be able to discern the level of attenuation in dB. I'm going to assume the amount is less than 1 dB.

My request is that we raise the attenuation amount to 1 dB to completely avoid clipping samples.

**Comment by lasconic** [comment]
For the record, the bug in libsndfile is https://musescore.org/en/node/21814. See in particular the full history here: https://musescore.org/en/node/22086

In the current code, my understanding is that the amplification is 20log10(32768/35000) = -0.572362dB

For -1dB, the magic number would be 1/((1/32768)*pow(10.0, -1 / 20.0)) = 36766.30

@wschweer Any thoughts on this issue?

**Comment by lasconic** [comment]
I added an option `-a` to pass an amplification factor in dB.

**Comment by lasconic** [comment]
Tests welcome :) 
I also added `-q` for the ogg compression quality. Default is 0.3.

**Comment by mrbumpy409** [comment]
Just compiled the new version and can see the new options listed when I run "sfconvert --help". However, trying to use either -a or -q throws an error:
`sfconvert: invalid option -- 'a'`
I'm trying to run the command as follows:
`sfconvert -z -a -1.0 input.sf2 output.sf3`

**Comment by lasconic** [comment]
My mistake indeed. Fixed and tested.
