### ISSUE TITLE
Request for relicencing

### ISSUE THREAD

**Issue by mirabilos** [musescore/sftools#29]
MuseScore-sftools are currently GPLv2-only.

Now other software, such as the [Polyphone](https://www.polyphone-soundfonts.com/) soundfont editor, may [wish to reuse the code](https://github.com/davy7125/polyphone/issues/105). Polyphone is, however, under GPLv3.

It would be nice if MuseScore-sftools could be relicenced to GPLv2-or-later. To do this, all relevant copyright holders will have to agree to the following change: replace `under the terms of the GNU General Public License version 2.` in all source files with `under the terms of the GNU General Public License version 2.` with `under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.`

That would legalise Polyphone again and help others in reusing.

A move to LGPLv2-or-later would make this code available to an even wider public, and I would love to see it, but it’s not a strict requirement. For this, use: `under the terms of the GNU Library General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.`

Thanks in advance!

**Comment by mirabilos** [comment]
Polyphone [might need](https://github.com/davy7125/polyphone/issues/107) a [GPL exception for OpenSSL](https://spdx.org/licenses/openvpn-openssl-exception.html) if you switch to GPLv2-or-later (first suggestion).

With LGPL, this won’t be a problem of course.

**Comment by anatoly-os** [comment]
I will double check with the lawyer and will apply the changes if there's no problem with that.

**Comment by mirabilos** [comment]
anatoly-os dixit:

>I will double check with the lawyer and will apply the changes if
>there's no problem with that.

Thank you!

**Comment by mirabilos** [comment]
ping?

**Comment by mirabilos** [comment]
@anatoly-os any progress on that? @davy7125 needs this for SF3 support in Polyphone…

**Comment by anatoly-os** [comment]
Oh, dear. Sorry. What we need to do is just change the license file in this repo. That's all. We are eligible to do that any time.

**Comment by mirabilos** [comment]
@anatoly-os okay, I opened https://github.com/musescore/sftools/pull/30 with proposed wording (straight from the “How to Apply These Terms to Your New Libraries” part of the LGPL and the official SPDX text for the OpenSSL exception), which you can merge **iff** you agree with this and wish to grant this slightly more liberal (but still copyleft-protect) licence.

**Comment by mirabilos** [comment]
Thanks @anatoly-os !

I’ll tell the Polyphone people to rebase their changes on the latest, relicenced, codebase then.
