### ISSUE TITLE
Please add support for SF3 sound fonts in fluidsynth

### ISSUE THREAD

**Issue by fabiangreffrath** [musescore/sftools#8]
Hi there,

I believe it would be a fair move to create a patch that adds support for your single-handedly introduced new sound font format to fluidsynth. See https://sourceforge.net/p/fluidsynth/tickets/142/

Thank you very much!
- Fabian

**Comment by lasconic** [comment]
We didn't know if it would fly when we tried this. Thank you for your work on fluidsynth.
There is now support for SF3 in [FluidSynth](https://github.com/FluidSynth/fluidsynth/issues/140), in [Polyphone](https://github.com/davy7125/polyphone) and in [FluidLite](https://github.com/divideconcept/FluidLite).

**Comment by trebmuh** [comment]
...and [LMMS](https://github.com/LMMS/lmms/pull/3895), and [Qtractor](https://github.com/rncbc/qtractor/).
